# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               想做美丽的程序媛
tagline:             'be happy'
description:         '此博客上传usaco前3.2章题目解答'
url:                 http://whuan20011.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Kate
  url:               https://whuan20011.github.io

# Custom vars
version:             1.0.0
