# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               ğŸ‘¸æƒ³åšç¾ä¸½çš„ç¨‹åºåª›ğŸ‘¸
tagline:             'ğŸ’•ğŸ’•ğŸ’•'
description:         'æ­¤åšå®¢ä¸Šä¼ usacoå‰3.2ç« é¢˜ç›®è§£ç­”'
url:                 http://whuan20011.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Kate
  url:               https://whuan20011.github.io

# Custom vars
version:             1.0.0
